name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #optional to use a specific node version, might as well.
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci # installs dependencies, similar to npm install
      - run: npm run format:check # run the script we wrote
      - run: npm test -- --coverage # Run tests with code coverage
        env:
          CI: true # set that CI variable to true.
