name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Optionally, use a different version of node.
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          npm: "6.x"

      - name: List Files
        run: |
          pwd
          ls -l
      - name: Install Dependencies
        run: npm install # installs dependencies, similar to npm install
      - name: Check formatting
        run: npm run format:check
      - name: Run tests
        run: npm test -- --coverage
        env:
          CI: true
