name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Optionally, use a different version of node.
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci # installs dependencies, similar to npm install
      - name: Check formatting
        run: npm run format:check
      - name: Run tests
        run: npm test -- --coverage
        env:
          CI: true
